### ISSUE TITLE
Layout for BM15

### ISSUE THREAD

**Issue by oaken-source** [tuxedocomputers/keyboard-layouts#10]
Looking at the top-shots of both the XP15 (https://www.tuxedocomputers.com/store_files/1/images/product_images/popup_images/38098.jpg) and the BM15 (https://www.tuxedocomputers.com/store_files/1/images/product_images/popup_images/37869.jpg) does the template from the XP15 apply to the BM15 as well?

**Comment by vinzv** [comment]
Sorry, unfortunately not.
