### ISSUE TITLE
ANSI vs ISO

### ISSUE THREAD

**Issue by vrde** [tuxedocomputers/keyboard-layouts#25]
Hello!

I noticed that for the *Pulse 15* the [US ANSI layout](https://github.com/tuxedocomputers/keyboard-layouts/blob/4989fc0342426b17d2a15c987f8c1109768d2548/Pulse%2015/Pulse15%20US-ANSI.svg) and [US ISO layout](https://github.com/tuxedocomputers/keyboard-layouts/blob/4989fc0342426b17d2a15c987f8c1109768d2548/Pulse%2015/Pulse15%20US-ISO.svg) are exactly the same, while in the [Keyboards & Layout page on the company's website](https://www.tuxedocomputers.com/en/Infos/Help-Support/Frequently-asked-questions/Keyboards-Layouts_1.tuxedo) they are different.

## ANSI

This is the ANSI keyboard in the repo:

![image](https://user-images.githubusercontent.com/134680/110629007-fd0be680-81a3-11eb-8e7b-2bb93609c6f1.png)

And this is the one from the Tuxedo website:

![image](https://user-images.githubusercontent.com/134680/110629066-101eb680-81a4-11eb-8ddd-d90563e61f28.png)

**As you can see the `enter` keys are different, and the layout in this repo is incorrect.**

## ISO

This is the ISO keyboard in the repo:

![image](https://user-images.githubusercontent.com/134680/110629033-039a5e00-81a4-11eb-852e-6db22f52e5ec.png)

And this is the one from the Tuxedo website:

![image](https://user-images.githubusercontent.com/134680/110629083-144ad400-81a4-11eb-9d89-37010399f595.png)

**Comment by vinzv** [comment]
Please have a closer look:

![image](https://user-images.githubusercontent.com/74432/111314979-38a22700-8662-11eb-819a-dac3a1f1c9a0.png)

![image](https://user-images.githubusercontent.com/74432/111315090-553e5f00-8662-11eb-8611-4b6bb683fa5e.png)

**Comment by vrde** [comment]
I'm referring to the shape of the enter key, in this repo the enter key is "vertical", in the tuxedo website the enter key is "horizontal".

![image](https://user-images.githubusercontent.com/134680/111430192-4efbc180-86fa-11eb-86e9-cb553d7c08b9.png)

**Comment by vinzv** [comment]
Yes, that's why the layer is labelled "JUST FOR ORIENTATION". You can see that by opening the file in Inkscape.

Long story short: submitting a custom layout based on this file you will get a proper ANSI layout.
