### ISSUE TITLE
Pulse15 US-ISO and US-ANSI key confusion

### ISSUE THREAD

**Issue by themancalledjakob** [tuxedocomputers/keyboard-layouts#50]
hi,

i want to design my own keyboard layout for a Pulse 15, and am a bit confused by the available templates. 

I notice that the backslash is found twice on the [Pulse 15/Pulse15 US-ISO.svg](https://raw.githubusercontent.com/tuxedocomputers/keyboard-layouts/master/Pulse%2015/Pulse15%20US-ISO.svg) and there is a big enter (incl backslash?) and multiple empty keys for the [Pulse 15/Pulse 15 US-ANSI](https://raw.githubusercontent.com/tuxedocomputers/keyboard-layouts/master/Pulse%2015/Pulse15%20US-ANSI.svg).

Is this a mistake? On the pictures on tuxedocomputers.com of the Pulse 15 I can only see the German ISO layout, without any repeating keys.

**Comment by vinzv** [comment]
Hi,

Sorry for the late reply!

Just stating for others who might read this: 
Our grid is always ISO but that doesn't matter for production as the etching laser doesn't care about the grid lines and just for the placement of key labels.
