### ISSUE TITLE
Kind request to clarify ANSI vs. ISO on website

### ISSUE THREAD

**Issue by dandv** [tuxedocomputers/keyboard-layouts#67]
Hi, I've just discovered the ability to customize the keyboard layout for Tuxedo notebooks, great to see this!

I was reading the [Keyboards & Layouts](https://www.tuxedocomputers.com/en/Infos/Help-Support/Frequently-asked-questions/Keyboards-Layouts_1.tuxedo) page and I'm unclear on the "Differences ISO vs. ANSI" section. Could images be added there to illustrate the two different physical layouts, perhaps the images from the [InfinityBook Pro 14 Gen 6](https://www.tuxedocomputers.com/en/Linux-Hardware/Linux-Notebooks/10-14-inch/TUXEDO-InfinityBook-Pro-14-Gen6.tuxedo)?

I'm asking because looking at some layouts in this repo, [ANSI](https://github.com/tuxedocomputers/keyboard-layouts/blob/4989fc0342426b17d2a15c987f8c1109768d2548/Pulse%2015/Pulse15%20US-ANSI.svg) and [ISO](https://github.com/tuxedocomputers/keyboard-layouts/blob/4989fc0342426b17d2a15c987f8c1109768d2548/Pulse%2015/Pulse15%20US-ISO.svg) are the same physically (only the symbols differ), but in the image I linked above, they are different: [ANSI](https://www.tuxedocomputers.com/store_files/1/images/content/kb_ansi.png) has a wider left <kbd>shift</kbd> key, shorter <kbd>return</kbd> key, and an extra <kbd>\\</kbd> key vs. the [ISO](https://www.tuxedocomputers.com/store_files/1/images/content/kb_iso.png).

**Comment by vinzv** [comment]
See https://github.com/tuxedocomputers/keyboard-layouts/blob/master/README.md on this repository.

Quoting:

> The grid is always created for ISO layouts, but is ignored by the laser. ANSI layouts can therefore also be created with it without any problems!
