### ISSUE TITLE
Why isn't this linked to in your web sites keyboard info page?

### ISSUE THREAD

**Issue by meyerovb** [tuxedocomputers/keyboard-layouts#74]
Woulda been super helpful, had to go to reddit to find this.

**Comment by vinzv** [comment]
It's there:
Bottom of the Page -> https://www.tuxedocomputers.com/en/Individual-Keyboards.tuxedo -> https://www.tuxedocomputers.com/en/Infos/Help-Support/Instructions/Keyboard-laser-etching-and-logo-printing-service.tuxedo
